// AUTO-GENERATED by scripts/gen-article-loaders.mjs — do not edit by hand.
// Run `pnpm articles:gen` after adding or removing an article .mdx file.
import type React from "react";

export const LOADERS: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  "ai-search-vs-google-perth": () => import("@/content/articles/ai-search-vs-google-perth.mdx"),
  "google-business-profile-ai-recommend": () => import("@/content/articles/google-business-profile-ai-recommend.mdx"),
  "we-asked-chatgpt-best-tradies-perth": () => import("@/content/articles/we-asked-chatgpt-best-tradies-perth.mdx"),
  "website-invisible-to-ai-fixes": () => import("@/content/articles/website-invisible-to-ai-fixes.mdx"),
  "your-next-customer-wont-scroll-google": () => import("@/content/articles/your-next-customer-wont-scroll-google.mdx"),
};
