// AUTO-GENERATED by scripts/gen-article-loaders.mjs — do not edit by hand.
// Run `pnpm articles:gen` after adding or removing an article .mdx file.
import type React from "react";

export const LOADERS: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  "your-next-customer-wont-scroll-google": () => import("@/content/articles/your-next-customer-wont-scroll-google.mdx"),
};
